---
- block:
  - name: install php components
    apt: "pkg={{ item }} state=latest"
    with_items:
      - php-fpm
      - php-mysql
      - php7.0-opcache
      - php-curl
      - php-gd
      - php-imagick
      - php-mcrypt
      - php-ldap
      - php-geoip
  tags:
    - php
