---
- block:
  - name: install php components
    apt: "pkg={{ packages }} state=latest"
    vars:
      packages:
      - php-fpm
      - php-mysql
      - php-curl
      - php-gd
      - php-imagick
      - php-mcrypt
      - php-ldap
      - php-geoip
      - php-zip
      - php7.0-opcache
      - php7.0-xml
  tags:
    - php
